Hw1
gavrilovds/tinkoff-java-course pull request #2
Opened 2023-10-04 10:43 UTC by gavrilovds

Выполненная домашняя работа #1 (задания 0-8)

2023-10-07 17:36 UTC, SHvatov requested changes

2023-10-07 17:36 UTC, SHvatov commented on src/test/java/edu/hw1/task3/ArraysUtilsTest.java
> +        int[] testArray1 = new int[] {1, 2, 3, 4};
а почему в этом тесте параметры не параметризованы?

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task4/StringUtils.java
> +    private static final Logger LOGGER = LogManager.getLogger();
не используется

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task4/StringUtils.java
> +    public static String fixString(String toFix) {
`toFix` неочевидное название для переменной, лучше все-таки, чтобы это было существительное, а не глагол

можно, к примеру, `messedUpString`

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task5/PalindromeUtils.java
> +        if (String.valueOf(number).length() % 2 != 0 || number < 0) {
новая строка порождается здесь и на 12 строке, можно обойтись и одной

и точно ли тут нужна конвертация в строку? нельзя обойтись математическими операциями?

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task5/PalindromeUtils.java
> +        while (tempString.length() >= 2) {
Алгоритм получился очень сложными, давай перепишем его через остатки и рекурсию?

По поводу кода - название переменной `flag` не самое удачное. Оно мало говорит о предназначении переменной и для чего она используется.

2023-10-07 17:36 UTC, SHvatov commented on src/test/java/edu/hw1/task5/PalindromeUtilsTest.java
> +        "-11211230, false"
почему отрицательное значение не подходит?

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task6/PermanentCaprekarUtils.java
> +        LOGGER.info(increased + " " + decreased);
лог мало о чем говорящий, хорошо бы его сделать более подробным

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task6/PermanentCaprekarUtils.java
> +        int increased = Integer.parseInt(sortedNum);
названия переменных неочевидные, может largerNumber & lowerNumber?

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task6/PermanentCaprekarUtils.java
> +        char[] digits = String.valueOf(number).toCharArray();
алгоритм со строками хорош по времени, однако по памяти он сложноват - слишком много строк создаем) давай попробуем без строк решить данную задачу?

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task7/BitUtils.java
> +        LOGGER.info(binary);
не очень бы хотелось смотреть на бинарные строки в логах)

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task7/BitUtils.java
> +                newNumber.replace(i - shift, i - shift + 1,
скобочки и переносы не единообразны, но это к вопросу о едином код-стайле

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task7/BitUtils.java
> +public final class BitUtils {
очень много новых строк и преобразований из инта в строку, давай попробуем сделать через битовые операции?

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task8/ChessUtils.java
> +    private static List<Pair<Integer, Integer>> moves = new ArrayList<>();
может быть final

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task8/ChessUtils.java
> +    private static final String MESSAGE = "Wrong input";
`ERROR_MESSAGE`, а то не понятно о каком сообщении идет речь

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task8/ChessUtils.java
> +    private static List<Pair<Integer, Integer>> moves = new ArrayList<>();
и по коду лучше бы это была локальная переменная

2023-10-07 17:36 UTC, SHvatov commented on src/main/java/edu/hw1/task8/ChessUtils.java
> +                        } catch (ArrayIndexOutOfBoundsException e) {
1. catch без обработки сообщения - плохая практика, так лучше не делать
2. Снова же - лучше добавить базовые проверки на валидность индексов, чем ловить исключение и его игнорить. _Все-таки исключения предполагают исключительную ситуацию, требующую особой обработки._

2023-10-07 18:17 UTC, gavrilovds commented on src/main/java/edu/hw1/task0/HelloWorld.java
> +    private static final Logger LOGGER = LogManager.getLogger();
А это не будет конфликтовать с код стайлом Тинькофф? Просто в проект ведь уже добавлен кодстайл, если я не ошибаюсь. Функцию автоформатирования (ctrl+alt+l) вроде всегда прожимал.

2023-10-07 18:24 UTC, gavrilovds commented on src/test/java/edu/hw1/task1/VideoUtilsTest.java
> +    public void testTime_shouldReturnCorrectAnswer_whenInputIsCorrect(String testTime, int expected) {
На сайтах читал, что это стиль такой для написания названий для тестов, также спрашивал у семинариста, он как раз и посоветовал так называть.

![image](https://github.com/gavrilovds/tinkoff-java-course/assets/74236778/88d1fceb-0fca-4f11-a935-9f1f5b8a4a67)

2023-10-07 18:28 UTC, gavrilovds commented on src/test/java/edu/hw1/task3/ArraysUtilsTest.java
> +        int[] testArray1 = new int[] {1, 2, 3, 4};
Не нашел способа, как параметризировать массивы. Как будто там какие-то костыльные методы на мой взгляд, но возможно я ошибаюсь.

2023-10-07 19:25 UTC, SHvatov commented on src/main/java/edu/hw1/task0/HelloWorld.java
> +    private static final Logger LOGGER = LogManager.getLogger();
В проекте я вижу только чек-стайл для плагина `maven-checkstyle-plugin`, но не полноценный код-стайл. К примеру, код-стайл нашей команды регулирует все, вплоть до кол-ва пустых строк между блоками кода. Я просто предлагаю попробовать подключить гугловый код-стайл и пройтись по проекту, чтобы привести код в проекте к единому виду.

2023-10-07 19:26 UTC, SHvatov commented on src/test/java/edu/hw1/task1/VideoUtilsTest.java
> +    public void testTime_shouldReturnCorrectAnswer_whenInputIsCorrect(String testTime, int expected) {
понял принял, от команды к команде это варьируется, но такой нейминг я вижу в первый раз) я уточню, будет ли у нас какой-то общий подход к неймингу и отпишусь.

2023-10-07 19:27 UTC, SHvatov commented on src/test/java/edu/hw1/task1/VideoUtilsTest.java
> +    public void testTime_shouldReturnCorrectAnswer_whenInputIsCorrect(String testTime, int expected) {
пока что давай тогда так оставим, есои что - бахнешь минорный рефакторинг

2023-10-07 21:31 UTC, gavrilovds commented on src/main/java/edu/hw1/task0/HelloWorld.java
> +    private static final Logger LOGGER = LogManager.getLogger();
Поставил в итоге Гугловский код стайл, прокликал везде ctrl alt shift, вроде как особо ничего не изменилось. 
<img width="340" alt="image" src="https://github.com/gavrilovds/tinkoff-java-course/assets/74236778/8d511ce3-5907-4501-85ae-1524e7a91c09">
Кстати, вот эта галочка будет работать, если работать из терминала, а не из Idea? А то привык из терминала с гитом работать.
<img width="321" alt="image" src="https://github.com/gavrilovds/tinkoff-java-course/assets/74236778/b2953a77-750d-44df-aa57-5a32797c6957">

2023-10-08 18:28 UTC, SHvatov commented on src/main/java/edu/hw1/task0/HelloWorld.java
> +    private static final Logger LOGGER = LogManager.getLogger();
Поменялось :) Теперь везде код +- единообразен. 

<img width="1452" alt="image" src="https://github.com/gavrilovds/tinkoff-java-course/assets/15994914/d63b3327-8d43-4f35-9ffe-d5ea28ea9a1e">

2023-10-08 18:31 UTC, SHvatov commented on src/test/java/edu/hw1/task3/ArraysUtilsTest.java
> +        int[] testArray1 = new int[] {1, 2, 3, 4};
На будущее - [Argument Source](https://www.baeldung.com/parameterized-tests-junit-5#6-method). В следующих домашках можно будет заиспользовать.

2023-10-08 18:34 UTC, SHvatov commented on src/main/java/edu/hw1/task1/VideoUtils.java
> +        int minutes = Integer.parseInt(videoLength.split(":")[0]);
На будущее - лучше результат сплита сохранить в переменную и использовать ее, чем два раза вызывать сплит.

2023-10-08 18:35 UTC, SHvatov commented on src/main/java/edu/hw1/task2/DigitsUtils.java
> +    public static final int STEP = 10;
Константу лучше сделать приватной, так как она нигде не используется кроме как в классе, а публичное пространство имен загрязняет.

2023-10-08 18:35 UTC, SHvatov commented on src/main/java/edu/hw1/task5/PalindromeUtils.java
> +    public static final int BASE = 10;
Аналогично.

2023-10-08 18:36 UTC, SHvatov commented on src/main/java/edu/hw1/task5/PalindromeUtils.java
> +        int nextNumber = getNextNumber(reversed);
ИМХО, лучше `descendant`.

2023-10-08 18:37 UTC, SHvatov commented on src/main/java/edu/hw1/task7/BitUtils.java
> +        return (number << newShift | number >> (numberOfBits - newShift)) & ((1 << numberOfBits) - 1);
красивое :)

2023-10-08 18:37 UTC, SHvatov approved these changes

2023-10-08 18:37 UTC, SHvatov approved these changes

2023-10-08 18:38 UTC, SHvatov approved these changes

2023-10-08 18:51 UTC, gavrilovds commented on src/main/java/edu/hw1/task5/PalindromeUtils.java
> +        int nextNumber = getNextNumber(reversed);
Мне сначала поправить это, а потом мержить, так?

2023-10-08 19:11 UTC, merged